# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdiff < Formula
  desc "Fast directory comparison and interactive HTML diff report CLI tool"
  homepage "https://github.com/ivanlunardi/kdiff"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivanlunardi/kdiff/releases/download/v1.0.1/kdiff_1.0.1_darwin_amd64.tar.gz"
      sha256 "29f9ba02f00d7bc493b3ee1f754380aee52a0b8efc874967209c95150d2ae097"

      define_method(:install) do
        bin.install "kdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivanlunardi/kdiff/releases/download/v1.0.1/kdiff_1.0.1_darwin_arm64.tar.gz"
      sha256 "a58e65ce5ca61114dceee70e09e835c0412266bdd49768c2d33d8ee62b4e09d0"

      define_method(:install) do
        bin.install "kdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivanlunardi/kdiff/releases/download/v1.0.1/kdiff_1.0.1_linux_amd64.tar.gz"
      sha256 "bf1a87256bad27f58d0eaea65acd17a7aaab7ea7b68511287896d6f30e2df21f"
      define_method(:install) do
        bin.install "kdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivanlunardi/kdiff/releases/download/v1.0.1/kdiff_1.0.1_linux_arm64.tar.gz"
      sha256 "bd6cc02da72bee39f43a2fa77297513cf5efd1b38f3e7e6fcc39a36b3fa50445"
      define_method(:install) do
        bin.install "kdiff"
      end
    end
  end

  test do
    system "#{bin}/kdiff", "version"
  end
end
