# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdiff < Formula
  desc "Fast directory comparison and interactive HTML diff report CLI tool"
  homepage "https://github.com/ivanlunardi/kdiff"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivanlunardi/kdiff/releases/download/v1.0.2/kdiff_1.0.2_darwin_amd64.tar.gz"
      sha256 "b5f00e7c259546e1948363065211610a4e7f5e7444d67947e94fa2bedb5712c2"

      define_method(:install) do
        bin.install "kdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivanlunardi/kdiff/releases/download/v1.0.2/kdiff_1.0.2_darwin_arm64.tar.gz"
      sha256 "4647de4a35e4bce0df0d286359ee72279447aa343a74b41563af1f21160ce68c"

      define_method(:install) do
        bin.install "kdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivanlunardi/kdiff/releases/download/v1.0.2/kdiff_1.0.2_linux_amd64.tar.gz"
      sha256 "641bf6b12d6961a1f4066e321e5dfc31d3a55066cc0b556eb2bb41cdf30aa52e"
      define_method(:install) do
        bin.install "kdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivanlunardi/kdiff/releases/download/v1.0.2/kdiff_1.0.2_linux_arm64.tar.gz"
      sha256 "3ad93a12dd34f52e4277272f54ebf633cbea3a12b721745c6b70e0143ad0ae8e"
      define_method(:install) do
        bin.install "kdiff"
      end
    end
  end

  test do
    system "#{bin}/kdiff", "version"
  end
end
